# Generated by Django 4.2.20 on 2025-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "storybooks",
            "0003_remove_question_text_book_created_at_book_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="age_group",
            field=models.IntegerField(
                choices=[(3, "3+ ขวบ"), (4, "4+ ขวบ"), (5, "5+ ขวบ")],
                default=3,
                help_text="ช่วงอายุที่เหมาะกับนิทาน",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(null=True, upload_to="book_covers/"),
        ),
        migrations.AlterField(
            model_name="book", name="description", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="book_pdfs/"),
        ),
    ]
