# Generated by Django 4.2.20 on 2025-03-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storybooks", "0004_question_age_group_alter_book_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="age_group",),
        migrations.AddField(
            model_name="book",
            name="age_group",
            field=models.IntegerField(
                choices=[(3, "3+ ขวบ"), (4, "4+ ขวบ"), (5, "5+ ขวบ")],
                default=3,
                help_text="ช่วงอายุที่เหมาะกับนิทาน",
            ),
        ),
    ]
