# Generated by Django 4.2.20 on 2025-03-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storybooks", "0005_remove_question_age_group_book_age_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="age_group",
            field=models.IntegerField(
                choices=[(3, "3 ปีขึ้นไป"), (4, "4-5 ปีขึ้นไป"), (6, "6-7 ปีขึ้นไป")],
                default=3,
                help_text="ช่วงอายุที่เหมาะกับนิทาน",
            ),
        ),
    ]
