# Generated by Django 4.2.20 on 2025-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storybooks", "0006_alter_book_age_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="question", name="page", field=models.IntegerField(default=1),
        ),
    ]
