# Generated by Django 4.2.20 on 2025-03-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storybooks", "0007_question_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="double_page",
            field=models.BooleanField(default=False),
        ),
    ]
